name: Mirror ipyniivue gh-pages

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout ipyniivue gh-pages branch
      - name: Checkout ipyniivue gh-pages
        uses: actions/checkout@v4
        with:
          repository: niivue/ipyniivue
          ref: gh-pages
          path: ipyniivue-gh-pages
          fetch-depth: 1

      # Step 2: Clone your personal repository
      - name: Clone personal repository
        run: |
          git clone https://github.com/AnthonyAndroulakis/ipyniivue-docs.git personal-gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # Step 3: Check if gh-pages branch exists, if not, create it
      - name: Setup gh-pages branch
        run: |
          cd personal-gh-pages
          git fetch origin gh-pages || true
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard
          cd ..
      
      # Step 4: Sync content
      - name: Sync content
        run: |
          rsync -a --delete ipyniivue-gh-pages/ personal-gh-pages/

      # Step 5: Commit and push changes
      - name: Commit and push changes
        working-directory: personal-gh-pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update from ipyniivue gh-pages"
            git push origin gh-pages
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
