name: Deploy content to gh-pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        repository: niivue/ipyniivue
        ref: gh-pages
        path: source_repo

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        external_repository: ${{ github.repository }}
        publish_branch: gh-pages
        publish_dir: ./source_repo
